const nflTeams = [
  {
    name: "Arizona Cardinals",
    division: "NFC West",
    conference: "NFC",
    founded: "September 17, 1920",
    nflJoined: "1920",
    city: "Glendale",
    state: "AZ",
    cityFounded: "October 10, 1910",
    cityCharter: "October 10, 1910",
    stadium: "State Farm Stadium",
    stadiumOpened: "August 1, 2006"
  },
  {
    name: "Atlanta Falcons",
    division: "NFC South",
    conference: "NFC",
    founded: "June 30, 1965",
    nflJoined: "1966",
    city: "Atlanta",
    state: "GA",
    cityFounded: "1837",
    cityCharter: "December 29, 1847",
    stadium: "Mercedes-Benz Stadium",
    stadiumOpened: "August 26, 2017"
  },
  {
    name: "Baltimore Ravens",
    division: "AFC North",
    conference: "AFC",
    founded: "February 9, 1996",
    nflJoined: "1996",
    city: "Baltimore",
    state: "MD",
    cityFounded: "August 8, 1729",
    cityCharter: "January 13, 1797",
    stadium: "M&T Bank Stadium",
    stadiumOpened: "September 6, 1998"
  },
  {
    name: "Buffalo Bills",
    division: "AFC East",
    conference: "AFC",
    founded: "October 28, 1959",
    nflJoined: "1960",
    city: "Buffalo",
    state: "NY",
    cityFounded: "1810",
    cityCharter: "April 20, 1832",
    stadium: "Highmark Stadium",
    stadiumOpened: "August 17, 1973"
  },
  {
    name: "Carolina Panthers",
    division: "NFC South",
    conference: "NFC",
    founded: "October 26, 1993",
    nflJoined: "1995",
    city: "Charlotte",
    state: "NC",
    cityFounded: "December 3, 1768",
    cityCharter: "December 3, 1768",
    stadium: "Bank of America Stadium",
    stadiumOpened: "September 1, 1996"
  },
  {
    name: "Chicago Bears",
    division: "NFC North",
    conference: "NFC",
    founded: "September 17, 1920",
    nflJoined: "1920",
    city: "Chicago",
    state: "IL",
    cityFounded: "March 4, 1837",
    cityCharter: "March 4, 1837",
    stadium: "Soldier Field",
    stadiumOpened: "October 9, 1924"
  },
  {
    name: "Cincinnati Bengals",
    division: "AFC North",
    conference: "AFC",
    founded: "May 23, 1967",
    nflJoined: "1968",
    city: "Cincinnati",
    state: "OH",
    cityFounded: "December 1788",
    cityCharter: "March 1, 1819",
    stadium: "Paycor Stadium",
    stadiumOpened: "August 19, 2000"
  },
  {
    name: "Cleveland Browns",
    division: "AFC North",
    conference: "AFC",
    founded: "April 20, 1945",
    nflJoined: "1950",
    city: "Cleveland",
    state: "OH",
    cityFounded: "July 22, 1796",
    cityCharter: "January 1, 1914",
    stadium: "Huntington Bank Field",
    stadiumOpened: "September 12, 1999"
  },
  {
    name: "Dallas Cowboys",
    division: "NFC East",
    conference: "NFC",
    founded: "January 28, 1960",
    nflJoined: "1960",
    city: "Arlington",
    state: "TX",
    cityFounded: "1876",
    cityCharter: "1884",
    stadium: "AT&T Stadium",
    stadiumOpened: "May 27, 2009"
  },
  {
    name: "Denver Broncos",
    division: "AFC West",
    conference: "AFC",
    founded: "August 14, 1959",
    nflJoined: "1960",
    city: "Denver",
    state: "CO",
    cityFounded: "November 22, 1858",
    cityCharter: "November 7, 1861",
    stadium: "Empower Field at Mile High",
    stadiumOpened: "September 10, 2001"
  },
  {
    name: "Detroit Lions",
    division: "NFC North",
    conference: "NFC",
    founded: "July 12, 1930",
    nflJoined: "1930",
    city: "Detroit",
    state: "MI",
    cityFounded: "July 24, 1701",
    cityCharter: "September 13, 1806",
    stadium: "Ford Field",
    stadiumOpened: "September 22, 2002"
  },
  {
    name: "Green Bay Packers",
    division: "NFC North",
    conference: "NFC",
    founded: "August 11, 1919",
    nflJoined: "1921",
    city: "Green Bay",
    state: "WI",
    cityFounded: "1854",
    cityCharter: "February 27, 1854",
    stadium: "Lambeau Field",
    stadiumOpened: "September 29, 1957"
  },
  {
    name: "Houston Texans",
    division: "AFC South",
    conference: "AFC",
    founded: "October 6, 1999",
    nflJoined: "2002",
    city: "Houston",
    state: "TX",
    cityFounded: "August 30, 1836",
    cityCharter: "June 5, 1837",
    stadium: "NRG Stadium",
    stadiumOpened: "August 24, 2002"
  },
  {
    name: "Indianapolis Colts",
    division: "AFC South",
    conference: "AFC",
    founded: "January 23, 1953",
    nflJoined: "1953",
    city: "Indianapolis",
    state: "IN",
    cityFounded: "January 6, 1821",
    cityCharter: "March 30, 1847",
    stadium: "Lucas Oil Stadium",
    stadiumOpened: "August 16, 2008"
  },
  {
    name: "Jacksonville Jaguars",
    division: "AFC South",
    conference: "AFC",
    founded: "November 30, 1993",
    nflJoined: "1995",
    city: "Jacksonville",
    state: "FL",
    cityFounded: "June 15, 1822",
    cityCharter: "February 9, 1832",
    stadium: "EverBank Stadium",
    stadiumOpened: "August 18, 1995"
  },
  {
    name: "Kansas City Chiefs",
    division: "AFC West",
    conference: "AFC",
    founded: "August 14, 1959",
    nflJoined: "1960",
    city: "Kansas City",
    state: "MO",
    cityFounded: "June 3, 1850",
    cityCharter: "March 28, 1853",
    stadium: "GEHA Field at Arrowhead Stadium",
    stadiumOpened: "August 12, 1972"
  },
  {
    name: "Las Vegas Raiders",
    division: "AFC West",
    conference: "AFC",
    founded: "January 30, 1960",
    nflJoined: "1960",
    city: "Las Vegas",
    state: "NV",
    cityFounded: "May 15, 1905",
    cityCharter: "March 16, 1911",
    stadium: "Allegiant Stadium",
    stadiumOpened: "July 31, 2020"
  },
  {
    name: "Los Angeles Chargers",
    division: "AFC West",
    conference: "AFC",
    founded: "August 14, 1959",
    nflJoined: "1960",
    city: "Inglewood",
    state: "CA",
    cityFounded: "February 7, 1908",
    cityCharter: "February 7, 1908",
    stadium: "SoFi Stadium",
    stadiumOpened: "September 8, 2020"
  },
  {
    name: "Los Angeles Rams",
    division: "NFC West",
    conference: "NFC",
    founded: "February 12, 1937",
    nflJoined: "1937",
    city: "Inglewood",
    state: "CA",
    cityFounded: "February 7, 1908",
    cityCharter: "February 7, 1908",
    stadium: "SoFi Stadium",
    stadiumOpened: "September 8, 2020"
  },
  {
    name: "Miami Dolphins",
    division: "AFC East",
    conference: "AFC",
    founded: "August 16, 1965",
    nflJoined: "1966",
    city: "Miami Gardens",
    state: "FL",
    cityFounded: "May 13, 2003",
    cityCharter: "May 13, 2003",
    stadium: "Hard Rock Stadium",
    stadiumOpened: "August 16, 1987"
  },
  {
    name: "Minnesota Vikings",
    division: "NFC North",
    conference: "NFC",
    founded: "January 28, 1960",
    nflJoined: "1961",
    city: "Minneapolis",
    state: "MN",
    cityFounded: "1872",
    cityCharter: "1872",
    stadium: "U.S. Bank Stadium",
    stadiumOpened: "July 22, 2016"
  },
  {
    name: "New England Patriots",
    division: "AFC East",
    conference: "AFC",
    founded: "November 22, 1959",
    nflJoined: "1960",
    city: "Foxborough",
    state: "MA",
    cityFounded: "June 10, 1778",
    cityCharter: "June 10, 1778",
    stadium: "Gillette Stadium",
    stadiumOpened: "May 11, 2002"
  },
  {
    name: "New Orleans Saints",
    division: "NFC South",
    conference: "NFC",
    founded: "November 1, 1966",
    nflJoined: "1967",
    city: "New Orleans",
    state: "LA",
    cityFounded: "Spring 1718",
    cityCharter: "March 7, 1805",
    stadium: "Caesars Superdome",
    stadiumOpened: "August 3, 1975"
  },
  {
    name: "New York Giants",
    division: "NFC East",
    conference: "NFC",
    founded: "August 1, 1925",
    nflJoined: "1925",
    city: "East Rutherford",
    state: "NJ",
    cityFounded: "March 29, 1894",
    cityCharter: "March 29, 1894",
    stadium: "MetLife Stadium",
    stadiumOpened: "April 10, 2010"
  },
  {
    name: "New York Jets",
    division: "AFC East",
    conference: "AFC",
    founded: "August 14, 1959",
    nflJoined: "1960",
    city: "East Rutherford",
    state: "NJ",
    cityFounded: "March 29, 1894",
    cityCharter: "March 29, 1894",
    stadium: "MetLife Stadium",
    stadiumOpened: "April 10, 2010"
  },
  {
    name: "Philadelphia Eagles",
    division: "NFC East",
    conference: "NFC",
    founded: "July 8, 1933",
    nflJoined: "1933",
    city: "Philadelphia",
    state: "PA",
    cityFounded: "1682",
    cityCharter: "October 25, 1701",
    stadium: "Lincoln Financial Field",
    stadiumOpened: "August 3, 2003"
  },
  {
    name: "Pittsburgh Steelers",
    division: "AFC North",
    conference: "AFC",
    founded: "July 8, 1933",
    nflJoined: "1933",
    city: "Pittsburgh",
    state: "PA",
    cityFounded: "November 27, 1758",
    cityCharter: "March 18, 1816",
    stadium: "Acrisure Stadium",
    stadiumOpened: "August 18, 2001"
  },
  {
    name: "San Francisco 49ers",
    division: "NFC West",
    conference: "NFC",
    founded: "June 4, 1944",
    nflJoined: "1950",
    city: "Santa Clara",
    state: "CA",
    cityFounded: "January 12, 1777",
    cityCharter: "July 5, 1852",
    stadium: "Levi's Stadium",
    stadiumOpened: "July 17, 2014"
  },
  {
    name: "Seattle Seahawks",
    division: "NFC West",
    conference: "NFC",
    founded: "June 4, 1974",
    nflJoined: "1976",
    city: "Seattle",
    state: "WA",
    cityFounded: "May 23, 1853",
    cityCharter: "December 2, 1869",
    stadium: "Lumen Field",
    stadiumOpened: "July 20, 2002"
  },
  {
    name: "Tampa Bay Buccaneers",
    division: "NFC South",
    conference: "NFC",
    founded: "April 24, 1974",
    nflJoined: "1976",
    city: "Tampa",
    state: "FL",
    cityFounded: "January 18, 1849",
    cityCharter: "December 15, 1855",
    stadium: "Raymond James Stadium",
    stadiumOpened: "September 20, 1998"
  },
  {
    name: "Tennessee Titans",
    division: "AFC South",
    conference: "AFC",
    founded: "August 14, 1959",
    nflJoined: "1960",
    city: "Nashville",
    state: "TN",
    cityFounded: "December 24, 1779",
    cityCharter: "April 23, 1806",
    stadium: "Nissan Stadium",
    stadiumOpened: "September 12, 1999"
  },
  {
    name: "Washington Commanders",
    division: "NFC East",
    conference: "NFC",
    founded: "July 9, 1932",
    nflJoined: "1932",
    city: "Landover",
    state: "MD",
    cityFounded: "",
    cityCharter: "",
    stadium: "Commanders Field",
    stadiumOpened: "September 14, 1997"
  }
];
